services:
  # Web Service - Node.js Express Application (POSTGRESQL MODE)
  - type: web
    name: iase-project-web
    env: node
    buildCommand: bash render-pre-deploy.sh && bash render-alchemy-install.sh && npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      # Configurazione ambiente - PRODUZIONE
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: "error"
      - key: IASE_DEBUG
        value: "false"
      - key: ENABLE_FALLBACK_SYSTEM
        value: "true"
      
      # Configurazione percorsi
      - key: PUBLIC_PATH
        value: "/app/public"
      - key: STATIC_PATH
        value: "/app/public"
      - key: CONFIG_PATH
        value: "/app/config"
      - key: ALTERNATIVE_PUBLIC_PATH
        value: "/opt/render/project/src/public"
      
      # Configurazione database
      - key: USE_MEMORY_DB
        value: "false"
      - key: SKIP_DB_CONNECTION
        value: "false"
      - key: PGHOST
        value: dpg-d0ff45buibrs73ekrt6g-a.oregon-postgres.render.com
      - key: PGUSER
        value: iaseproject
      - key: PGDATABASE
        value: iaseproject
      - key: PGPASSWORD
        value: GRxrehk6Isv8s3dS3KDJFQ3HMVlxc8k1
      - key: PGPORT
        value: "5432"
      - key: DATABASE_URL
        value: postgresql://iaseproject:GRxrehk6Isv8s3dS3KDJFQ3HMVlxc8k1@dpg-d0ff45buibrs73ekrt6g-a.oregon-postgres.render.com/iaseproject
      
      # Configurazione sicurezza
      - key: SESSION_SECRET
        value: iase-project-secure-session-key-render-deployment
      - key: JWT_SECRET
        value: iase-project-jwt-secret-key-render-deployment
        
      # Configurazione blockchain - Alchemy (primario)
      - key: ALCHEMY_API_KEY
        value: uAZ1tPYna9tBMfuTa616YwMcgptV_1vB
      - key: ALCHEMY_API_URL
        value: https://eth-mainnet.g.alchemy.com/v2/uAZ1tPYna9tBMfuTa616YwMcgptV_1vB
      - key: USE_ALCHEMY_API
        value: "true"
      - key: ALCHEMY_ENHANCED_APIS
        value: "true"
      - key: ALCHEMY_NETWORK
        value: "1"
      
      # Retrocompatibilità - Ethereum (fallback)
      - key: INFURA_API_KEY
        value: 84ed164327474b4499c085d2e4345a66
      - key: ETH_NETWORK_URL
        value: https://mainnet.infura.io/v3/84ed164327474b4499c085d2e4345a66
      - key: ETHEREUM_RPC_FALLBACK
        value: https://rpc.ankr.com/eth
      
      # Configurazione blockchain - BSC
      - key: BSC_RPC_URL
        value: https://bsc-dataseed.binance.org/
      - key: BSC_RPC_FALLBACK
        value: https://bsc-dataseed1.defibit.io/
      
      # Indirizzi contratti
      - key: NFT_CONTRACT_ADDRESS
        value: 0x8792beF25cf04bD5B1B30c47F937C8e287c4e79F
      - key: REWARDS_CONTRACT_ADDRESS
        value: 0x38C62fCFb6a6Bbce341B41bA6740B07739Bf6E1F
      - key: REWARD_DISTRIBUTOR_CONTRACT
        value: 0x38c62fcfb6a6bbce341b41ba6740b07739bf6e1f
      - key: TOKEN_CONTRACT_ADDRESS
        value: 0x5A170D59ae8B851DC4DD0D14cC89E5fE541752CE
        
      # Ottimizzazioni per Render
      - key: OPTIMIZE_RENDER
        value: "true"
      - key: COMPRESSION_ENABLED
        value: "true"
      
      # Configurazione dati reali - PRODUZIONE
      - key: USE_REAL_DATA
        value: "true"
      - key: DISABLE_TEST_MODE
        value: "true"
      - key: BLOCKCHAIN_NETWORK
        value: "mainnet"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=1024"
    autoDeploy: true

  # Cron job for daily NFT verification at midnight
  - type: cron
    name: nft-verification-job
    env: node
    schedule: "0 0 * * *"  # Run at midnight every day
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js --mode=verification
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_MEMORY_DB
        value: "false"
      - key: SKIP_DB_CONNECTION
        value: "false"
      - key: PGHOST
        value: dpg-d0ff45buibrs73ekrt6g-a.oregon-postgres.render.com
      - key: PGUSER
        value: iaseproject
      - key: PGDATABASE
        value: iaseproject
      - key: PGPASSWORD
        value: GRxrehk6Isv8s3dS3KDJFQ3HMVlxc8k1
      - key: PGPORT
        value: "5432"
      - key: DATABASE_URL
        value: postgresql://iaseproject:GRxrehk6Isv8s3dS3KDJFQ3HMVlxc8k1@dpg-d0ff45buibrs73ekrt6g-a.oregon-postgres.render.com/iaseproject
      - key: INFURA_API_KEY
        value: 84ed164327474b4499c085d2e4345a66
      - key: ETH_NETWORK_URL
        value: https://mainnet.infura.io/v3/84ed164327474b4499c085d2e4345a66
      - key: ETHEREUM_RPC_FALLBACK
        value: https://rpc.ankr.com/eth
      - key: NFT_CONTRACT_ADDRESS
        value: 0x8792beF25cf04bD5B1B30c47F937C8e287c4e79F
      - key: REWARDS_CONTRACT_ADDRESS
        value: 0x38C62fCFb6a6Bbce341B41bA6740B07739Bf6E1F
      - key: REWARD_DISTRIBUTOR_CONTRACT
        value: 0x38c62fcfb6a6bbce341b41ba6740b07739bf6e1f
      - key: TOKEN_CONTRACT_ADDRESS
        value: 0x5A170D59ae8B851DC4DD0D14cC89E5fE541752CE
      - key: BSC_RPC_URL
        value: https://bsc-dataseed.binance.org/
      - key: BSC_RPC_FALLBACK
        value: https://bsc-dataseed1.defibit.io/
      - key: ENABLE_FALLBACK_SYSTEM
        value: "true"
      - key: OPTIMIZE_RENDER
        value: "true"
      - key: USE_REAL_DATA
        value: "true"
      - key: DISABLE_TEST_MODE
        value: "true"
      - key: BLOCKCHAIN_NETWORK
        value: "mainnet"