services:
  # Web Service - Node.js Express Application (NO DATABASE MODE)
  - type: web
    name: iase-project-web
    env: node
    buildCommand: npm install && npm run build
    startCommand: node simple-memory-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_MEMORY_DB
        value: "true"
      - key: SESSION_SECRET
        generateValue: true
      - key: ETH_NETWORK_URL
        value: https://eth.drpc.org
      - key: NFT_CONTRACT_ADDRESS
        value: 0x8792beF25cf04bD5B1B30c47F937C8e287c4e79F
      - key: REWARD_DISTRIBUTOR_CONTRACT
        value: 0x38c62fcfb6a6bbce341b41ba6740b07739bf6e1f
      - key: BSC_RPC_URL
        value: https://bsc-dataseed.binance.org/
    autoDeploy: true

  # Cron job for daily NFT verification at midnight
  - type: cron
    name: nft-verification-job
    env: node
    schedule: "0 0 * * *"  # Run at midnight every day
    buildCommand: npm install
    startCommand: USE_MEMORY_DB=true node server/services/staking-job.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_MEMORY_DB
        value: "true"
      - key: ETH_NETWORK_URL
        value: https://eth.drpc.org
      - key: NFT_CONTRACT_ADDRESS
        value: 0x8792beF25cf04bD5B1B30c47F937C8e287c4e79F
      - key: REWARD_DISTRIBUTOR_CONTRACT
        value: 0x38c62fcfb6a6bbce341b41ba6740b07739bf6e1f
      - key: BSC_RPC_URL
        value: https://bsc-dataseed.binance.org/

# Nessun database richiesto - utilizziamo storage in memoria